// paises.js
const countries = [
  { name: "Argentina", flag: "🇦🇷", currency: "Peso argentino (ARS)" },
  { name: "Australia", flag: "🇦🇺", currency: "Dólar australiano (AUD)" },
  { name: "Brasil", flag: "🇧🇷", currency: "Real brasileño (BRL)" },
  { name: "Canadá", flag: "🇨🇦", currency: "Dólar canadiense (CAD)" },
  { name: "China", flag: "🇨🇳", currency: "Yuan (CNY)" },
  { name: "Francia", flag: "🇫🇷", currency: "Euro (EUR)" },
  { name: "Alemania", flag: "🇩🇪", currency: "Euro (EUR)" },
  { name: "India", flag: "🇮🇳", currency: "Rupia india (INR)" },
  { name: "Japón", flag: "🇯🇵", currency: "Yen (JPY)" },
  { name: "México", flag: "🇲🇽", currency: "Peso mexicano (MXN)" },
  { name: "Rusia", flag: "🇷🇺", currency: "Rublo ruso (RUB)" },
  { name: "Reino Unido", flag: "🇬🇧", currency: "Libra esterlina (GBP)" },
  { name: "Estados Unidos", flag: "🇺🇸", currency: "Dólar estadounidense (USD)" },
  { name: "España", flag: "🇪🇸", currency: "Euro (EUR)" },
  { name: "Italia", flag: "🇮🇹", currency: "Euro (EUR)" },
  { name: "Sudáfrica", flag: "🇿🇦", currency: "Rand sudafricano (ZAR)" },
  { name: "Corea del Sur", flag: "🇰🇷", currency: "Won surcoreano (KRW)" },
  { name: "Turquía", flag: "🇹🇷", currency: "Lira turca (TRY)" },
  { name: "Nueva Zelanda", flag: "🇳🇿", currency: "Dólar neozelandés (NZD)" },
  { name: "Suiza", flag: "🇨🇭", currency: "Franco suizo (CHF)" },
  { name: "Suecia", flag: "🇸🇪", currency: "Corona sueca (SEK)" },
  { name: "Noruega", flag: "🇳🇴", currency: "Corona noruega (NOK)" },
  { name: "Dinamarca", flag: "🇩🇰", currency: "Corona danesa (DKK)" },
  { name: "Egipto", flag: "🇪🇬", currency: "Libra egipcia (EGP)" },
  { name: "Arabia Saudita", flag: "🇸🇦", currency: "Riyal saudí (SAR)" },
  { name: "Emiratos Árabes Unidos", flag: "🇦🇪", currency: "Dírham (AED)" },
  { name: "Nigeria", flag: "🇳🇬", currency: "Naira (NGN)" },
  { name: "Pakistán", flag: "🇵🇰", currency: "Rupia pakistaní (PKR)" },
  { name: "Indonesia", flag: "🇮🇩", currency: "Rupia indonesia (IDR)" },
  { name: "Malasia", flag: "🇲🇾", currency: "Ringgit malayo (MYR)" }
];

module.exports = countries;